language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir debug
  - cd debug
  - cmake ..
script: make
notifications:
  email:
    recipients:
      - congying1112@gmail.com
    on_success: change
    on_failure: always