language: cpp
compiler:
  - g++
  - clang++
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
before_script:
  - mkdir debug
  - cd debug
  - cmake ..
script: make
notifications:
  email:
    recipients:
      - congying1112@gmail.com
    on_success: change
    on_failure: always